"""init_db

Revision ID: 96f1de273877
Revises: 
Create Date: 2026-05-06 02:37:02.599554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96f1de273877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('uploaded', 'indexing', 'indexed', 'failed', name='sourcestatus').create(op.get_bind())
    sa.Enum('document', 'github', name='sourcetype').create(op.get_bind())
    sa.Enum('user', 'assistant', 'system', name='messagerole').create(op.get_bind())
    sa.Enum('admin', 'user', name='userrole').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('avatar', sa.JSON(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'user', name='userrole', create_type=False), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('forgot_password_token', sa.String(), nullable=True),
    sa.Column('forgot_password_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('last_compacted_message_id', sa.UUID(), nullable=True),
    sa.Column('needs_compaction', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_compacted_at', sa.DateTime(), nullable=True),
    sa.Column('recent_window_size', sa.Integer(), server_default='20', nullable=False),
    sa.Column('estimated_token_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('compaction_threshold', sa.Float(), server_default='0.85', nullable=False),
    sa.ForeignKeyConstraint(['last_compacted_message_id'], ['chat_messages.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('document', 'github', name='sourcetype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('uploaded', 'indexing', 'indexed', 'failed', name='sourcestatus', create_type=False), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', 'system', name='messagerole', create_type=False), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('chat_session_sources',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'source_id')
    )
    op.create_table('source_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('vector_indexed', sa.Boolean(), nullable=False),
    sa.Column('vector_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('graph_indexed', sa.Boolean(), nullable=False),
    sa.Column('graph_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('relation_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_indexes')
    op.drop_table('chat_session_sources')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    sa.Enum('admin', 'user', name='userrole').drop(op.get_bind())
    sa.Enum('user', 'assistant', 'system', name='messagerole').drop(op.get_bind())
    sa.Enum('document', 'github', name='sourcetype').drop(op.get_bind())
    sa.Enum('uploaded', 'indexing', 'indexed', 'failed', name='sourcestatus').drop(op.get_bind())
    # ### end Alembic commands ###